Slot Key Verification
snapshot-labs/sx-starknet pull request #121
Opened 2022-05-11 23:09 UTC by Orland0x

2022-05-17 10:13 UTC, pscott requested changes
Solid! Just a couple of nitpicks here and there.
One thing I would like to change though is naming! I think we need to come up with better naming, as I had a tough time differentiating `global_params` vs `global_params_all` etc etc.

To make sure I have a good understanding, what we have now is:
- `voting_strategy_params`: user-defined array of data
- `global_params`: voting strategy specific array, recorded in the `global_voting_strategy_params` storage var
- `global_params_all` and `voting_strategy_params_all`: a 2d immutable array consisting of all the different `global_params`. (`voting_strategy_params_all` is used in `get_cumulative_voting_power` and `global_params_all` in `register_global_voting_strategy_params`)

Is that correct?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/interfaces/i_voting_strategy.cairo
> +        block : felt,
may I ask why it got changed to a `block`?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/lib/array2d.cairo
> +    end
Maybe I'm sm0l brain but I think adding a little comment here to explain what we're doing would be beneficial for people reading the code! :) (It's understandable, but adding some comment will put more clarity as to what exactly we're doing :))

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/lib/felt_to_uint256.cairo
> +    let (high, _) = unsigned_div_rem(t1, SHIFT_8)
I fail to see why we don't directly bit shift by `128`, but maybe I'm completely missing something?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/lib/slot_key.cairo
> +func get_slot_key{bitwise_ptr : BitwiseBuiltin*, range_check_ptr}(
It would be nice to provide maybe some context as to `slot_index` and `mapping_key` refer to? Or give a link?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/lib/slot_key.cairo
> +    let (low, high) = unsafe_keccak(encoded_array, 64)
prefer `16 * 4` as it make it more evident that it's because we have 4 elements in encoded_array

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/lib/words64_to_uint256.cairo
> +# Convert a 4 words of 64 bits per felt to a Uint256 (128 bits per felt)
Convert 4 words of 64 bits* (remove `a`)

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/space.cairo
> +        else:
You can remove that, it's actually less step efficient :)

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/space.cairo
> +        else:
When I say that I mean l:317 - l:320

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/space.cairo
> +        assert _global_voting_strategy_params[index] = global_voting_strategy_param
I think we should put a comment here saying that we're actually assigning rather than `assert`-ing (even though it's the same thing in cairo). Or maybe remove the `assert`. This is because I believe the semantics around `x = y` is not the same as `assert x = y` and tbh I had to read this a couple of times in order to understand what was going on haha

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/space.cairo
> +        return (0)
Maybe I'm missing something but returning `0` seems odd to me? This means this function will always return `0`?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/space.cairo
> +    # Extract voting params array for the voting strategy specified by the index
Does using the `index` here work? 
while `get_cumulative_voting_power` used to iterate over all the voting strategies, now it only iterates through the `used_voting_strategies`. I *think* we need to change `index`, and actually find a way to find the corresponding `index` that corresponds to the `voting strategy`, right?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/space.cairo
> +func register_global_voting_strategy_params{
How about `unchecked_add_global_voting_strategy_params` ? To follow the other `unchecked_add` convention?

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
>  # FactRegistry simplified interface
Small detail but would appreciate a newline between the imports and the comment :)

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
>  func get_voting_power{
Maybe the expected `global_voting_params` should be defined here in the comments? I think it needs to be documented somewhere (for every new votingn strategy) so I think here is a good place :D

2022-05-17 10:13 UTC, pscott commented on test/starknet/lib_array2d.ts
> +  it('The library should be able to contruct the 2D array type from a flat array and then retrieve the sub arrays individually.', async () => {
construct*

2022-05-17 10:13 UTC, pscott commented on test/starknet/lib_array2d.ts
> +    expect(array1).to.deep.equal([BigInt(5)]);
I think we should `.to.deep.equal(arr1)`, in case we ever decide to change `arr1` :)

2022-05-17 10:13 UTC, pscott commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
>      alloc_locals
Should we first start by checking that `global_params_len == 2` ? I think currently the tests are running with this set to 0 (see my previous comment above), and still passing, because we're not checking this value?

2022-05-17 10:21 UTC, Orland0x commented
> Solid! Just a couple of nitpicks here and there. One thing I would like to change though is naming! I think we need to come up with better naming, as I had a tough time differentiating `global_params` vs `global_params_all` etc etc.
> 
> To make sure I have a good understanding, what we have now is:
> 
> * `voting_strategy_params`: user-defined array of data
> * `global_params`: voting strategy specific array, recorded in the `global_voting_strategy_params` storage var
> * `global_params_all` and `voting_strategy_params_all`: a 2d immutable array consisting of all the different `global_params`. (`voting_strategy_params_all` is used in `get_cumulative_voting_power` and `global_params_all` in `register_global_voting_strategy_params`)
> 
> Is that correct?

yeah this is what i used. i used 'params` and `global_params` when in the frame of reference of the voting strategy and `voting_strategy_params` and `global_voting_strategy_params` params when in the space contract frame.

2022-05-17 10:23 UTC, Orland0x commented on contracts/starknet/lib/felt_to_uint256.cairo
> +    let (high, _) = unsigned_div_rem(t1, SHIFT_8)
theres some limit of the divisor around 2^120 im pretty sure. bit annoying

2022-05-17 10:23 UTC, Orland0x commented on contracts/starknet/lib/array2d.cairo
> +    end
yep will do

2022-05-17 10:25 UTC, Orland0x commented on contracts/starknet/interfaces/i_voting_strategy.cairo
> +        block : felt,
fossil uses block numbers and we currently dont have a way to convert so we provide a block number here. Its on my to do list to add the conversion though, then will revert.

2022-05-17 10:26 UTC, Orland0x commented on contracts/starknet/lib/slot_key.cairo
> +func get_slot_key{bitwise_ptr : BitwiseBuiltin*, range_check_ptr}(
yep ill reference my repo https://github.com/snapshot-labs/evm-slot-key-verification

2022-05-17 10:26 UTC, Orland0x commented on contracts/starknet/lib/slot_key.cairo
> +    let (low, high) = unsafe_keccak(encoded_array, 64)
yep agree

2022-05-17 10:27 UTC, Orland0x commented on contracts/starknet/space.cairo
> +        else:
oh nice

2022-05-17 10:30 UTC, Orland0x commented on contracts/starknet/space.cairo
> +        assert _global_voting_strategy_params[index] = global_voting_strategy_param
i thought `x = y` was equivalent to `assert x = y`? i kind of use them interchangably but yeah would make more sense to stick to  `x = y` for assignments

2022-05-17 10:31 UTC, Orland0x commented on contracts/starknet/space.cairo
> +        return (0)
the function should never get there so it'll never return that, just put it there as you need a return statement. maybe this is a dumb way to do it?

2022-05-17 10:39 UTC, Orland0x commented on contracts/starknet/space.cairo
> +    # Extract voting params array for the voting strategy specified by the index
but now `voting_strategy_params_all` only contains the params for the strategies specified in `used_voting_strategies` so it should be ok?

2022-05-17 10:40 UTC, Orland0x commented on contracts/starknet/space.cairo
> +    # Extract voting params array for the voting strategy specified by the index
maybe we should rename `voting_strategy_params_all` to `used_voting_strategy_params` in this context

2022-05-17 10:40 UTC, Orland0x commented on contracts/starknet/space.cairo
> +func register_global_voting_strategy_params{
yep agree

2022-05-17 10:42 UTC, Orland0x commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
>  func get_voting_power{
yep agree

2022-05-17 10:42 UTC, Orland0x commented on test/starknet/lib_array2d.ts
> +    expect(array1).to.deep.equal([BigInt(5)]);
yep my bad

2022-05-17 10:43 UTC, Orland0x commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
>      alloc_locals
yep

2022-05-17 11:37 UTC, pscott commented on contracts/starknet/space.cairo
> +        assert _global_voting_strategy_params[index] = global_voting_strategy_param
Haha yes, they are the same in cairo but what I was tryingn to say with `semantics` is that, for a developer reading the code, he/she necessarily interpret both as being equal. I thought here we wanted to `assert` (meaning make sure that `_global_voting_strategy_params[index]` was equal to `global_voting_strategy_param` but what we're doing is indeed assigning a value to that... so I think removing the `assert` will make it more clear that we're doing just that! :)

2022-05-17 16:45 UTC, Orland0x commented on contracts/starknet/space.cairo
> +    # Extract voting params array for the voting strategy specified by the index
i did this

2022-05-18 10:50 UTC, pscott commented on contracts/starknet/lib/felt_to_uint256.cairo
> +    let (high, _) = unsigned_div_rem(t1, SHIFT_8)
Ah! Might be worth adding a comment to explain this :p

2022-05-18 11:01 UTC, pscott commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
> +    # contract address where the desired slot resides, and the section element is the index of the slot in that contract.
section element? You mean `second`?

2022-05-18 11:01 UTC, pscott commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
> +    assert global_params_len = 2
Maybe add
```
with_attr error_message("Incorrect length for global parameters"):
```
?

2022-05-18 11:01 UTC, Orland0x commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
> +    # contract address where the desired slot resides, and the section element is the index of the slot in that contract.
yep lol

2022-05-18 11:02 UTC, Orland0x commented on contracts/starknet/voting_strategies/single_slot_proof.cairo
> +    assert global_params_len = 2
yep

2022-05-18 11:05 UTC, pscott commented on contracts/starknet/space.cairo
> +        return (0)
I guess I don't understand something here. This function is supposed to return the `length` of the `_global_voting_strategy_params`, right?

In the case where `global_voting_strategy_param == 0` (meaning we've reached the end of the array) it returns `index` which seems fine to me

However I don't get why it should never return go in the `else` branch (and hence `return (0)`)?

2022-05-18 11:06 UTC, pscott commented on contracts/starknet/space.cairo
> +        return (0)
My intuition is that this function should actually return `global_voting_strategy_params_len` but maybe I'm wrong ^^

2022-05-18 16:25 UTC, pscott commented
> > Solid! Just a couple of nitpicks here and there. One thing I would like to change though is naming! I think we need to come up with better naming, as I had a tough time differentiating `global_params` vs `global_params_all` etc etc.
> > To make sure I have a good understanding, what we have now is:
> > 
> > * `voting_strategy_params`: user-defined array of data
> > * `global_params`: voting strategy specific array, recorded in the `global_voting_strategy_params` storage var
> > * `global_params_all` and `voting_strategy_params_all`: a 2d immutable array consisting of all the different `global_params`. (`voting_strategy_params_all` is used in `get_cumulative_voting_power` and `global_params_all` in `register_global_voting_strategy_params`)
> > 
> > Is that correct?
> 
> yeah this is what i used. i used `params` and `global_params` when in the frame of reference of the voting strategy (as voting strategy is implied) and `voting_strategy_params` and `global_voting_strategy_params` params when in the space contract frame.

What would you think about remove `strategy` (to make it less verbose) and use:
- `user_voting_params`: user-defined array of data
- `space_voting_params`: (or could be `protocol_voting_params` or `strategy_voting_params` or `constant_voting_params`. I think `global` sounds like it's common for all voting strategies?)

And maybe keeping the same naming for space / voting_strategies context, as it makes it easier to navigate the code and not get lost. Not sure about this last one, just my thoughts :)

2022-05-18 18:04 UTC, Orland0x commented
> > > Solid! Just a couple of nitpicks here and there. One thing I would like to change though is naming! I think we need to come up with better naming, as I had a tough time differentiating `global_params` vs `global_params_all` etc etc.
> > > To make sure I have a good understanding, what we have now is:
> > > 
> > > * `voting_strategy_params`: user-defined array of data
> > > * `global_params`: voting strategy specific array, recorded in the `global_voting_strategy_params` storage var
> > > * `global_params_all` and `voting_strategy_params_all`: a 2d immutable array consisting of all the different `global_params`. (`voting_strategy_params_all` is used in `get_cumulative_voting_power` and `global_params_all` in `register_global_voting_strategy_params`)
> > > 
> > > Is that correct?
> > 
> > 
> > yeah this is what i used. i used `params` and `global_params` when in the frame of reference of the voting strategy (as voting strategy is implied) and `voting_strategy_params` and `global_voting_strategy_params` params when in the space contract frame.
> 
> What would you think about remove `strategy` (to make it less verbose) and use:
> 
> * `user_voting_params`: user-defined array of data
> * `space_voting_params`: (or could be `protocol_voting_params` or `strategy_voting_params` or `constant_voting_params`. I think `global` sounds like it's common for all voting strategies?)
> 
> And maybe keeping the same naming for space / voting_strategies context, as it makes it easier to navigate the code and not get lost. Not sure about this last one, just my thoughts :)

I think its important we have `strategy` in the name as otherwise its not clear that they refer to parameters for voting strategies. Snapshot X is a voting protocol after all, so `voting_params` could conceivably refer to many different things. 

yeah `user_voting_params` makes sense I agree. 

hmmmm i see your point. Although to me, `space_voting_params` sounds more like it refers to something common to all strategies than `global_voting_params` does. Ill try to think of a better name...

yep i can keep same names with the space/voting strategy context. 

I think all of these ambiguities will be solved if we have a good natspec standard frankly

2022-05-18 18:12 UTC, Orland0x commented
we could do `user_voting_strategy_params` params and then just `voting_strategy_params` for the global ones?

2022-05-18 18:19 UTC, pscott commented
> we could do `user_voting_strategy_params` and then just `voting_strategy_params` for the global ones?

yes! There are three different variables though: the `user defined`, the `storage_var` (which takes all `voting_strategy_parameters` and what the `voting_strategy_parameters` storage_var holds.
Maybe we could do 

- `user_voting_strategy_params` 
- `voting_strategies_params` (for the storage var?)
- and the `voting_strategies_params` would store some `voting_strategy_params` ? 


The only issue I see is that it's hard to differentiate... or we could also do
- `user_voting_strategy_params`
- `global_voting_strategy_params` for the storage var
- and the storage var would store some `voting_strategy_params`

? wdyt?

2022-05-18 18:46 UTC, Orland0x commented
> > we could do `user_voting_strategy_params` and then just `voting_strategy_params` for the global ones?
> 
> yes! There are three different variables though: the `user defined`, the `storage_var` (which takes all `voting_strategy_parameters` and what the `voting_strategy_parameters` storage_var holds. Maybe we could do
> 
> * `user_voting_strategy_params`
> * `voting_strategies_params` (for the storage var?)
> * and the `voting_strategies_params` would store some `voting_strategy_params` ?
> 
> The only issue I see is that it's hard to differentiate... or we could also do
> 
> * `user_voting_strategy_params`
> * `global_voting_strategy_params` for the storage var
> * and the storage var would store some `voting_strategy_params`
> 
> ? wdyt?

why not just `voting_strategies_params_store`  for the storage var? tbh we could just make the `store` suffix a standard for every storage var in the contract

2022-05-19 09:24 UTC, pscott commented
> why not just `voting_strategy_params_store` for the storage var? tbh we could just make the `store` suffix a standard for every storage var in the contract. seems to be what starkware do anyway

I haven't seen this "standard" but i think it would be an excellent idea indeed. Should it be `store` or `storage`? (`store` sounds like it could be interpreted as a verb / action?)

2022-05-19 09:26 UTC, pscott commented
I know I'm being a little "picky" here, but I do think that we need to be careful about those as we will probably be setting the standard for the rest of the codebase and the future, and naming is an important and difficult task :p 

After all, as Phil Karlton said, *There are only two hard things in Computer Science: cache invalidation and naming things.* !

2022-05-19 09:38 UTC, Orland0x commented
> > why not just `voting_strategy_params_store` for the storage var? tbh we could just make the `store` suffix a standard for every storage var in the contract. seems to be what starkware do anyway
> 
> I haven't seen this "standard" but i think it would be an excellent idea indeed. Should it be `store` or `storage`? (`store` sounds like it could be interpreted as a verb / action?)

 cool lets do that then, `store` is generally used as a noun (like 'im going to store to get some eggs') so i think it makes sense slightly more sense to use here

2022-05-19 09:39 UTC, Orland0x commented
> I know I'm being a little "picky" here, but I do think that we need to be careful about those as we will probably be setting the standard for the rest of the codebase and the future, and naming is an important and difficult task :p
> 
> After all, as Phil Karlton said, _There are only two hard things in Computer Science: cache invalidation and naming things._ !

completely agree, crucial we get this space contract right.

2022-05-22 16:12 UTC, Orland0x commented
*think* all the fixes are in

2022-05-24 09:49 UTC, pscott approved these changes
💪

2022-05-24 09:50 UTC, pscott commented on contracts/starknet/space.cairo
> +# Setting the voting strategy to 0 will remove it from the store, but what happens if someone re-adds the strategy but with different params?
Btw I think we should indeed remove the associated voting strategy params :)

2022-05-24 10:03 UTC, merged