feat: prevent zero address for author/voter
snapshot-labs/sx-starknet pull request #492
Opened 2023-08-16 11:48 UTC by Orland0x

closes #488

2023-08-17 12:08 UTC, pscott requested changes
sorry I forgot to click "submit review" yesterday :(

2023-08-17 12:08 UTC, pscott commented on starknet/src/tests/test_space.cairo
> +    }
Erm I know you wrote a lot of the code but I would suggest to do these tests:

write a test module that only does a unit test on `is_zero` (could actually be inside of `user_address.cairo` tbh but doesn't have to).
In this unit test we try starknet, ethereum, and custom).

And then we actually test the three entrypoints (to get full code coverage and regression test), on `cancel`, `propose`, `update_proposal`, and `vote`. This time we don't care about whether they're starknet or ethereum, we just check to see if the code is here :)

2023-08-17 12:08 UTC, pscott commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
any reason we're not checking this for `cancel`?

If a DAO renounces ownership (sets owner to `0`), and then for some reason in a later starknet update there's a way to create txs with address zero (like when you deploy a contract or something...) then we'd be fucked. Doesn't cost much to add a check for `cancel` too imho! :)

2023-08-17 17:35 UTC, Orland0x commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
wdym? like preventing renounce ownership?

2023-08-17 18:04 UTC, pscott commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
hmm sorry i wasn't clear.
my question was " why no check on the `fn cancel()` function ?

2023-08-17 18:14 UTC, Orland0x commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
checking the caller address is not zero?

2023-08-17 18:53 UTC, pscott commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
yes

2023-08-17 20:30 UTC, Orland0x commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
seems like a crazy situation, would break so much if so that was the case. I think its safe to assume a caller cannot be the zero address. We would also need to check all setters etc too

Reason why its worth checking for `author`/`voter` is that its an argument so could quite easily be set to zero accidentally

2023-08-17 21:04 UTC, pscott commented on starknet/src/space/space.cairo
>              metadata_URI: Array<felt252>,
Yeah I guess you're right, it would break a lots of other stuff, not worth the trouble :)

2023-08-18 20:42 UTC, Orland0x commented on starknet/src/tests/test_space.cairo
> +    }
yep got the unit tests and all entry points tested. sorry was being a bit lazy

2023-08-21 08:55 UTC, pscott commented on starknet/src/tests/test_space.cairo
> +    }
nice, perfect

2023-08-21 09:00 UTC, pscott approved these changes
utACK, added some false positive tests

2023-08-23 15:35 UTC, merged